"""modified policy_history, add fk for policy

Revision ID: 11566f9ef232
Revises: 568d39b42b77
Create Date: 2025-08-07 01:19:35.472960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11566f9ef232'
down_revision: Union[str, Sequence[str], None] = '568d39b42b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_histories', sa.Column('policy_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('policy_histories_name_key'), 'policy_histories', type_='unique')
    op.create_foreign_key(None, 'policy_histories', 'policies', ['policy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'policy_histories', type_='foreignkey')
    op.create_unique_constraint(op.f('policy_histories_name_key'), 'policy_histories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('policy_histories', 'policy_id')
    # ### end Alembic commands ###
