"""add comment migration

Revision ID: e433ce87179b
Revises: 0a39924fe86c
Create Date: 2025-08-06 02:10:58.980542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e433ce87179b'
down_revision: Union[str, Sequence[str], None] = '0a39924fe86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'policies', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'policies', type_='unique')
    # ### end Alembic commands ###
